### ISSUE TITLE
Support for Consecutive and Restained WSI with DeeperHistReg

### ISSUE THREAD

**Issue by changwxx** [MWod/DeeperHistReg#7]
Hi! Thank you for your awesome work and for sharing the code. I have a question regarding DeeperHistReg: Does it support cases where there are several consecutive and restained WSI corresponding to a single wax cube? Additionally, how should one determine the appropriate registration pairs in such scenarios? Looking forward to your reply!

**Comment by MWod** [comment]
Hello,

Yes, you could use the framework for such cases (however, the patch-based registration method dedicated to the restained slides will be released soon - to improve the registration accuracy) as long as you have the slides in separate files (otherwise, you need to crop and save them separately before applying the registration).

You just need to define one reference slide and register all the remaining ones to the reference one. The decision related to the reference slide is usually not crucial but it may be wise to choose slide in the middle of the sample to decrease the risk of large nonrigid deformations.

In case your slides are strongly deformed and the registration accuracy is not perfect it may be better to register just the neighboring slides and then compose the deformation fields. This feature is currently available in the framework but it requires a bit of expertise in image registration.

Bests,

**Comment by changwxx** [comment]
Thank you for your response! Could you please point me to where I can find the function for `registering only the neighboring slides and composing the deformation fields` in the framework?

**Comment by MWod** [comment]
Hello,

In terms of the logic - you need to define which slides are neighbors and then register them using the provided pipeline. You repeat the procedure for every pair.

Afterwards, you can use [compose_displacement_fields](https://github.com/MWod/DeeperHistReg/blob/main/deeperhistreg/dhr_utils/warping.py#L111) function to compose the deformation fields before using the [apply_deformation](https://github.com/MWod/DeeperHistReg/blob/main/deeperhistreg/dhr_deformation/apply_deformation.py#L39).

It requires a bit of expertise because you need to implement the composition logic by yourself. We plan to release a 3-D reconstruction framework in the future, however, I cannot give any ETA for this.

Bests,
